import type { WatchlistStock } from "./types";

export const NIFTY_50_STOCKS: WatchlistStock[] = ([
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "ASIANPAINT", name: "Asian Paints" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "ITC", name: "ITC" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "NESTLEIND", name: "Nestle India" },
  { symbol: "NTPC", name: "NTPC" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corp" },
  { symbol: "POWERGRID", name: "Power Grid Corp" },
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "SUNPHARMA", name: "Sun Pharma" },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "TRENT", name: "Trent" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
] as { symbol: string; name: string }[]).map((s) => ({ ...s, closeWatch: false }));
